#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# Copyright (C) 2007,  Ahmet Emre Aladağ
#
# This program is free software; you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free
# Software Foundation; either version 2 of the License, or (at your option)
# any later version.
#
# Please read the COPYING file.
#

"""kiXdelta Main Program"""

from kdecore import * #KCmdLineArgs, KApplication
from kdeui import *  #kde ui libs
from kfile import *   #KURLRequester
from qt import * #Qt3 libs
from kixgui import * #Our Main Window
from about import about #Our About Dialog
import sys


if __name__ == "__main__":
	app = KApplication(sys.argv,"kiXdelta")
	f = Form1(app)
	app.setMainWidget(f)
	f.show()
	app.exec_loop()
	app.quit()